### ISSUE TITLE
Scanner AiO support

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-4-Davinci#163]
Host application based on Horus is here => https://github.com/luc-github/horus/tree/davinci - this is still in early stage of support - thanks @zeus10

**Comment by luc-github** [comment]
I think this issue is going to nowhere as no support for 2 years
I close it

**Comment by Toylerrr** [comment]
Sorry to dig this back up did this ever get working?

**Comment by luc-github** [comment]
nope
