### ISSUE TITLE
Sync with mainstream

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-4-Davinci#263]
Long this has not been done -  may be it is time to do it to grab latest fixes if any

**Comment by luc-github** [comment]
I am currently syncing with current devt branch of repetier to get latest fixes
Doing some code simplification, I am wondering if it is necessary to keep the easy/ advanced modes or to stay with only one complete mode like repetier does ?
 
So this would lead to use original repetier UI menu + specific menus of Davinci dispatched on different repetier submenus  and no more currrent fully customized one 

Any feedback on this ?

**Comment by cdoc83** [comment]
I vote for going with original repetier menu + additional DaVinci specific menus.

**Comment by rhinorap** [comment]
Seconded, but keep in mind that your menu structure is bang on with the current build and the repetier menus are somewhat.......clunky.

**Comment by luc-github** [comment]
The current menu for davinci is rewrited from repetier with feature not present in repetier and based on early discussion of usage which are little bit different than repetier spirit
This bring 80% of the work to maintain it because not really easy to do code difference on very different source code
This include repetier wizard mode and davinci wizard mode which are not compatibles...

That is why I was wondering if it worth to maintain Davinci UI. As I never got users feedback on it

**Comment by luc-github** [comment]
Now duplicate with https://github.com/luc-github/Repetier-Firmware-4-Davinci/issues/286
closing
