### ISSUE TITLE
Do you support da Vinci Nano Printer ?

### ISSUE THREAD

**Issue by butor32** [luc-github/Repetier-Firmware-4-Davinci#289]
Hi,
The processor are a Atmet ATSAM4S8C, not a DUE processor.
Does your project integrate this processor ?
Thanks from Belgium.

**Comment by luc-github** [comment]
There is currently no arduino support for sam4 mcu so no support for any printer using sam4 family
I do not know Davinci Nano, but on other sam4 based printer they use another mcu (M0 like) to control the temperature part making the porting even more difficult 
Sorry no support

**Comment by butor32** [comment]
Thank you for your prompt response
