### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by os40la** [luc-github/Repetier-Firmware-4-Davinci#292]
luc,
I think there is a typo in the url link. You have "RRepetier". I think you have a extra "R". If I remove the extra "R" the link works.

+Build Status: [![Build Status](https://travis-ci.org/luc-github/Repetier-Firmware-4-Davinci.svg?branch=master)](https://travis-ci.org/luc-github/RRepetier-Firmware-4-Davinci)

**Comment by luc-github** [comment]
fixed - thank you 😄
