### ISSUE TITLE
How do we support the DEV ?

### ISSUE THREAD

**Issue by rhinorap** [luc-github/Repetier-Firmware-4-Davinci#294]
Hi,
I think it's time there was a link to a donation page as the Dev has spent so long getting this branch right - and continues to do so.

**Comment by luc-github** [comment]
Thank you, there is a link in readme page actually, but no one seems to see it ;) 10 people in 3 years for less than 100€, no complain but  I am not relying on it ^_^

**Comment by luc-github** [comment]
I guess issue can be closed
