### ISSUE TITLE
filament change issue

### ISSUE THREAD

**Issue by tecan** [luc-github/Repetier-Firmware-4-Davinci#301]
when the printer runs out of filament during the print it would be nice if it reversed out the old filament before loading new filament. i had to recover a print because the z axis maxed out during the process too strange homing behavior.

**Comment by tecan** [comment]
im not sure if once it hits the sensor its too late to put it back into the tube in the top ?

**Comment by luc-github** [comment]
Yes indeed it is weird - loading/unloading is user responsability as many user case , no filament, clocked extruder/jam issue/ etc...
Stock sensor position is also little bit too close to extruder it should be more far to allow to take filament by hand.

**Comment by tecan** [comment]
i wonder if we can use the top door sensor for an extra filament detector somehow.

**Comment by luc-github** [comment]
you can use :
the Jam sensor pin which is not used
the door sensor pin 
the led pin - and connect led to power
the unpopulated connections of your board - some use pins

**Comment by tecan** [comment]
https://www.thingiverse.com/thing:3021660 made one of these, works good

**Comment by tecan** [comment]
https://cdn.thingiverse.com/renders/da/f5/24/e3/20/f2a1960ce7dafbbd2bfd6f6ee8af4442_preview_featured.JPG

**Comment by luc-github** [comment]
I guess issue can be closed
