### ISSUE TITLE
strange behavior for webserver.

### ISSUE THREAD

**Issue by tecan** [luc-github/Repetier-Firmware-4-Davinci#302]
i've been leaving the printer on at night, this morning i woke up to find an ip address on the display panel and it was not getting any commands from pronterface  it kept sending code 34 to pronterface while connected. i have no wifi chip installed either basically stock firmware.

**Comment by luc-github** [comment]
Something send a M117 XXX.xxx.xxx.xxx to your printer - it does not come FW itself
May be you have repetier host and server running on this PC also ?

**Comment by luc-github** [comment]
closing as no feedback
