### ISSUE TITLE
windows 7 device not recognized davinci 1.0a 

### ISSUE THREAD

**Issue by novyyyy** [luc-github/Repetier-Firmware-4-Davinci#303]
Hi

been having a few problems with my davinci 1.0a. i formatted my laptop that runs my server for my printer reinstalled windows 7 x64 and now i cannot connect to my printer. i have reset my printer j37 and have two black bars on lcd display ready to flash .

i followed a few youtube videos tutorials and info from google using older versions of arduino etc and i keep running in to this same problem with device not recognized .

after laptop format windows  it can see 3dprinter as bossa and as soon as i compile and upload, bossa disappears and i get device not recognized. two black bars are still on lcd at this point device not flashed 

any help appreciated or if anyone can link me to an updated 2018 davinci 1.0a hack tutorial using latest arduino 1.8.5 and latest FW.

**Comment by novyyyy** [comment]
EDIT:

i managed to get it working again following this guys tutorial https://www.youtube.com/watch?v=rjuCvlnpB7M&list=WL

ardueno version 1.5.8
FW version 0.92.3  dated 2015

**Comment by luc-github** [comment]
sorry for late reply and happy you handled it, windows can be difficult sometimes 
Happy printing
