### ISSUE TITLE
extra extruder support

### ISSUE THREAD

**Issue by tecan** [luc-github/Repetier-Firmware-4-Davinci#306]
was wondering if it were possible to add an i2c interface for adding extra digital and analog pins for other extruders and sensors.

https://imgur.com/m5NMMYi  not sure what j11 is for on this. or where to find extra io pins.

**Comment by luc-github** [comment]
Did you check the EEPROM cartridge pins ? they are free and connected

**Comment by tecan** [comment]
![1600x1400-img_3795](https://user-images.githubusercontent.com/172564/43099737-560f8d64-8e80-11e8-9f82-1f2d6c4c7f76.JPG)

i had 3 wires soldered on already which pins are these here ?

**Comment by luc-github** [comment]
VCC GND and Pin 115 ?
Checkhttps://github.com/luc-github/Repetier-Firmware-4-Davinci/blob/master/pinout.xlsx

**Comment by tecan** [comment]
also are the io pins rated for 5v ? or like arduino due and only like 3.5V ?

**Comment by luc-github** [comment]
vcc should be 3.3v

**Comment by tecan** [comment]
oh i see on the board com1 and com2 ports. awesome going to give this a whirl today hopefully.

**Comment by tecan** [comment]
![1600x1400-img_3796](https://user-images.githubusercontent.com/172564/43102238-c2fb9ff6-8e87-11e8-9069-374d0e74e4f6.JPG)

**Comment by tecan** [comment]
https://github.com/tecan/PCF8574-SWire-Arduino.git   had to modify it to use new pins. works at 3.3 volts with 8 new i/o pins

**Comment by tecan** [comment]
https://github.com/tecan/Adafruit_SSD1306-SWire-Arduino also this one for extra displays

**Comment by tecan** [comment]
can confirm it working on pins 115 116

**Comment by luc-github** [comment]
You connected esp01 with oled ?

**Comment by tecan** [comment]
esp8285 because of the powersave feature then to the i2c portion maybe. for now it just sits there unconnected. have a flashair card that just arrived i might play with first. i just put some of the test code to the setup and loop for now in repetier. will be digging more into it later hopefully to add new olcd support.

**Comment by tecan** [comment]
https://github.com/tecan/PortExpander_I2C-SWire-Arduino   there we go, turns out this is better i2c library for PCF8574.    the other lib was doing the pin reads backwards
 it likes steady high read state then pull to ground for action,otherwise the pins could not trigger eachother.
https://github.com/skywodd/pcf8574_arduino_library/issues/14

**Comment by luc-github** [comment]
this is the olded I use on ESP3D - easy to program

**Comment by luc-github** [comment]
I guess issue can be closed
