### ISSUE TITLE
M109 cooling

### ISSUE THREAD

**Issue by tecan** [luc-github/Repetier-Firmware-4-Davinci#307]
M109 Set Extruder Temperature and Wait needs to have cooling too.
instead of S other firmwares use R.  M190 for the hotend would be good too.

Snn
Rnnn

**Comment by tecan** [comment]
in commands.cpp i see

if (com->hasS()) Extruder::setHeatedBedTemperature(com->S,com->hasF() && com->F > 0);

not sure what F is doing but maybe we could use that.

**Comment by luc-github** [comment]
you mean using standard GCODE the temperature does not wait and cool down ?

**Comment by tecan** [comment]
yes

**Comment by luc-github** [comment]
I think instead of add new parameter better to request fix such issue. Wait for T temperature should not be if heating or cool down. Just reach temperature

**Comment by luc-github** [comment]
Did you get feedback from repetier ?

I close as not davinci related
