### ISSUE TITLE
Printer bed not stopping on the top menus screw is jittery

### ISSUE THREAD

**Issue by RandomCow64** [luc-github/Repetier-Firmware-4-Davinci#308]
Flashed my davinchi 1.0a with the number j35 and the first thing I see on the menu screen of my davinchi is a whole bunch of exclamation marks . So I think this is normal and I navigate to home axies and start the home all x and y home fine but the z just keeps on going past the sensor is it something I can fix what should I do

**Comment by luc-github** [comment]
Did you use MODEL 1 in configuration.h ? as looks typical issue of wrong configuration

**Comment by luc-github** [comment]
I think issue can be closed as no update
