### ISSUE TITLE
Cannot compile the code from arduino to the printer[CLOSED]

### ISSUE THREAD

**Issue by OAAbaali2896** [luc-github/Repetier-Firmware-4-Davinci#309]
Hi,
I cannot compile the code and the error message states 
**Board arduino_due_x (platform sam, package arduino) is unknown
Error compiling for board Arduino Due (Native USB Port).**
I saved my file, from installing, in desktop & I didn't change anything in it. I only replaced the hardware file from repetier to 
C:\Users\osama_gc25s5w\AppData\Local\Arduino15\packages\arduino\hardware
I followed the instructions and I appreciate with the help.

**Comment by OAAbaali2896** [comment]
I can finally compile the code with the USB port attached. The issue was using 1.8.4 rather than 1.8.0, I don't know why.

**Comment by luc-github** [comment]
Sorry for late reply and happy printing
