### ISSUE TITLE
Encrypted GCode Decoder

### ISSUE THREAD

**Issue by tecan** [luc-github/Repetier-Firmware-4-Davinci#310]
feature request
aes ,rsa or something like openssl encrypted gcode processing, each machine could store its own unique rsa key.

https://gist.github.com/thinkerbot/706137 Openssl file encoder

might appeal more to the private sectors and people who want to sell/licence models with the ability to expire. might even make security dongles possible.

**Comment by tecan** [comment]
perhaps a smartcard would work better for sending propritary gcodes that only print x ammount of times. or something like oauth ?

**Comment by tecan** [comment]
have put the issue here aswell https://github.com/repetier/Repetier-Firmware/issues/807

**Comment by luc-github** [comment]
Hi seems I missed several tickets - sorry for this -  I received other repository tickets but this one seems silent....

About decoder - sorry I have no time to add new features on repetier4Davinci
The best is what you did to submit to mainstream
