### ISSUE TITLE
Install issue. CPU Reset not working after install.

### ISSUE THREAD

**Issue by wirelessguyny** [luc-github/Repetier-Firmware-4-Davinci#313]
I have a Davinci 2.0 Duo (1st gen/ J1) and have tried the upload a number of times.
The IDE says success with the upload but the board never resets. I continue to see the #####.

If I power off/on my USB then keeps connecting and then disconnecting. Display still reads ####

I need to short jumper J1 again and restart the process in order for the USB device to be recognized (Bossa Programming Port) once again.

I don't know if there is a soft reset capability. I don't see any buttons on the board.

Thoughts?

**Comment by wirelessguyny** [comment]
I followed the post form Issue #114 and put the files in the correct path. Lowered Baud rate on Bossa to 1200 and reflashed. While I did not get any different result on screen (i.e. #### still there), this time power off/on DID bring up the new Firmware.

**Comment by luc-github** [comment]
Sorry looks like I did not get notifications because was disabled ...

yes after flash always need to rebootas mentioned in readme

`9 - Once flash is done : restart printer`

Happy you managed
