### ISSUE TITLE
Z-Axis don't work

### ISSUE THREAD

**Issue by thefelix93123** [luc-github/Repetier-Firmware-4-Davinci#316]
Hi
I repaired my printer, maybe you remember (#315 )
Now the X and Y- axis are working correctly, but the Z axis don't move. I took the plug from another axis and tryed to move the z axis, but also no reaction, so the hardware should be ok.

And the second problem is, the extruder 1 turns in the wrong direction.

it's a da vinci 2 duo, motherboard with jp37.

do you have a idea what the problem is?

**Comment by luc-github** [comment]
No - the code did not changed since a while and was working

Is it a working 2.0A stock FW or a second hand ? I am surprised the axis end stop were broken so easily

I am guessing the second extruder is not wired properly, but this can be changed in FW and
I supect also  Z motor has also wiring issue

just in case export EEPROM settings using repetier host and post here

**Comment by thefelix93123** [comment]
It was a second hand printer :/  
<img width="474" alt="firmware config" src="https://user-images.githubusercontent.com/26041388/46168415-1903c200-c2a1-11e8-9ecb-0cf0d9efaa74.PNG">
<img width="463" alt="firmware config2" src="https://user-images.githubusercontent.com/26041388/46168416-1903c200-c2a1-11e8-8b4a-b88bce6575f8.PNG">
<img width="443" alt="firmware config3" src="https://user-images.githubusercontent.com/26041388/46168417-1903c200-c2a1-11e8-812a-59fc3caf204c.PNG">
<img width="435" alt="firmware config4" src="https://user-images.githubusercontent.com/26041388/46168418-1903c200-c2a1-11e8-925c-6c9600dbf571.PNG">
<img width="440" alt="firmware config5" src="https://user-images.githubusercontent.com/26041388/46168419-199c5880-c2a1-11e8-84be-3aa3643ec9dc.PNG">
<img width="432" alt="firmware config6" src="https://user-images.githubusercontent.com/26041388/46168420-199c5880-c2a1-11e8-997b-90f3d34ca920.PNG">

[https://drive.google.com/open?id=1ROW1zXEGR5bpaSmgq9Df2LaWdTPG5Ggz](url)   and this is the eeprom file

**Comment by luc-github** [comment]
Yeah second and modifed printer 
Check the extruder wires / connector - I won't be surprised if the wires were cut and reassembled, in worst case just change direction in FW
for Z you need to investigate : 

Check Z motor wires you can check continuity between board connector and motor

I guess sensor are working as you can see the temperature but I would also suggest you to check if printer is heating bed / extruder 1 / extruder 2 you may have others surprises

**Comment by luc-github** [comment]
if wires are Ok I would guess step drivers issue or sensor issue - you see check sensor state when you press key down on printer

**Comment by thefelix93123** [comment]
the sensor is ok :/ i also tried another sensor..  on this board i can't change the driver. is there anywhere a fuse?  or need i a new board?

**Comment by luc-github** [comment]
I do not think it is fuse issue 

I suggest to ask on forum some advice , like in http://www.soliforum.com/ section Davinci - this may happen to someone else - 
as it is hardware issue - here is not the best place to get help - I only have a duo first generation

**Comment by thefelix93123** [comment]
ok, i will try it there
thank you very much

**Comment by luc-github** [comment]
good luck
