### ISSUE TITLE
Marlin 2.0 port

### ISSUE THREAD

**Issue by ffnull** [luc-github/Repetier-Firmware-4-Davinci#319]
Please write me on email xxxx@xxxxx 
Im need your help in porting marlin 2.0 Allmost all already done but im stuck on some things

**Comment by luc-github** [comment]
It is bad idea to give emal like this - bots can use it and spam you - I remove it 
no need email you can use gitter and private message
 you can login with github account : https://gitter.im/luc-github/Repetier-Firmware-0.92
