### ISSUE TITLE
During calibration the text refers to "a sheet of paper" what is assumed

### ISSUE THREAD

**Issue by The-Experimentalist** [luc-github/Repetier-Firmware-4-Davinci#320]
Hi Luc

During calibration the text refers to "a sheet of paper" what is assumed to be the thickness of the paper?

0.1mm?
0.2mm?

I use feeler gauges to calibrate the printer and I am customising my code again and would rather refer to a specific size than to a "a sheet of paper".

Obviously the "a sheet of paper" is assumed to be of a certain thickness and the calibration is based on that. I hope you can help.

All the best 
Ex.

**Comment by limited660** [comment]
A sheet of paper is typically .004" (around .1mm) but as long as what you use is consistent it doesn't really matter as you can adjust Z offset to get the correct first layer.

**Comment by The-Experimentalist** [comment]
Thanks, where do you configure Z offset?

**Comment by limited660** [comment]
I adjust the Z offset in the Slicer.

**Comment by The-Experimentalist** [comment]
Thanks, what Slicer do you use out of interest? I tend to use Cura that is built in to Repetier for convenience.

**Comment by limited660** [comment]
I use Simplify3D, Kisslicer, and Slic3rPE

**Comment by luc-github** [comment]
I guess issue can be closed
