### ISSUE TITLE
Support for Da Vinci Mini W

### ISSUE THREAD

**Issue by ghost** [luc-github/Repetier-Firmware-4-Davinci#323]
is it possible for you to create firmware for the Da Vinci Mini W? I will be happy to test it, I'm just tired of paying to much for NFC protected filament...

**Comment by luc-github** [comment]
Sorry I do not have such printer so will be hard for me to hack it.
but can you take picture of printer 's  board and specialy  get the mcu I can see see if it is possible at least
is W for wireless ?

**Comment by 2xrgmdak** [comment]
![download](https://user-images.githubusercontent.com/34389063/46591163-81f7f080-ca7e-11e8-9d21-1e6f17ff39f6.jpg)
![image](https://user-images.githubusercontent.com/34389063/46591213-d26f4e00-ca7e-11e8-968e-a799205f732e.png)

here is an image of the mother board, sorry its not my image... i stole it off google. I havnt had the chance to take my printer apart. Yes the W stands for wirless, i have never acctually set up the wifi on it, but there is the option. I am unsure what you mean by MCU

**Comment by luc-github** [comment]
The big chip with Atmel on it . need more close picture of it

**Comment by 2xrgmdak** [comment]
Okay, I will look around on google.  If I can’t find one I will have to open my printer up and take a picture for you tomorrow.

**Comment by 2xrgmdak** [comment]
![img_1580](https://user-images.githubusercontent.com/34389063/46592851-1d439280-ca8c-11e8-9fa4-40470d369535.PNG)
here you go

**Comment by 2xrgmdak** [comment]
![img_1580](https://user-images.githubusercontent.com/34389063/46592903-7b707580-ca8c-11e8-97cb-d59e89884da7.PNG)
here you go

**Comment by luc-github** [comment]
Looks like same as jr and pro which need a lot of work to avoid hack they split temperature with another cpu than the atmel one which make hacking more difficult

**Comment by luc-github** [comment]
The positive is seems no screen
I do not SD card reader so I guess use software host is mandatory
I do no see how the wifi works if no screen / sd

**Comment by 2xrgmdak** [comment]
You have to open the xyz slicer and connect it to WiFi, then you can just send .3W files to it.

**Comment by 2xrgmdak** [comment]
And yes, the xyz ware slicer is mandatory. But I have found I can send .gcode to it using “windows print 3D”

**Comment by luc-github** [comment]
you mean you send 3W file then can disconnect ? or xyz slicer  stream the file ?
is there any SD card ?

**Comment by 2xrgmdak** [comment]
There is no sd card. Yes, once you send the gcode file to the printer you can disconnect it from the computer

**Comment by luc-github** [comment]
It means there is some flash to store the file which is new feature

**Comment by luc-github** [comment]
Close a user was deleted - so no more request
