### ISSUE TITLE
G-Code to perform a power on reset of the printer?

### ISSUE THREAD

**Issue by The-Experimentalist** [luc-github/Repetier-Firmware-4-Davinci#324]
Is there any G-Code that you can use to perform a power on reset of the printer?

**Comment by luc-github** [comment]
https://github.com/luc-github/Repetier-Firmware-4-Davinci/blob/master/src/ArduinoDUE/Repetier/Repetier.ino

M112

**Comment by The-Experimentalist** [comment]
Thanks
