### ISSUE TITLE
M303 command syntax for heated bed?

### ISSUE THREAD

**Issue by The-Experimentalist** [luc-github/Repetier-Firmware-4-Davinci#327]
I have read the comments in Repetier.ino but I'm not sure I understand the syntax of the M303 command to tune the heated bed. Could you post an example?

**Comment by The-Experimentalist** [comment]
Actually please could you also post an example for extruder 1?

**Comment by luc-github** [comment]
I have never used sorry
You can check https://reprap.org/wiki/G-code#M303:_Run_PID_tuning

**Comment by luc-github** [comment]
As no update I guess can close
