### ISSUE TITLE
Using manual bed level after changing nozzle on stock extruder for 1.0a

### ISSUE THREAD

**Issue by moorer2k** [luc-github/Repetier-Firmware-4-Davinci#335]
First off thanks for your hard work, always appreciated it.

So, I read similar issues but nothing really seemed to provide the exact answers for me. I recently purchased this product [XYZ Printing Da Vinci 1.0 Pro MK10 M7 Nozzle Adapter](https://www.etsy.com/listing/594312121/xyz-printing-da-vinci-10-pro-mk10-m7) for my 1.0a. Installed the z bracket for hitting the sensor, since it's about 9mm longer than the stock setup was.

When I home all the axis's, the nozzle is nice and clear from the the bed. When I go to manually level the bed, it raises the bed much higher than what the endstop is triggering at.. If I understand correctly, this has changed the standard z height defined in the firmware by AT LEAST -11mm? If I should ask this @ repetier forum I will head over there, and sorry to post at the wrong location.

**Comment by moorer2k** [comment]
Yeah I make sure when I home all axis's that the nozzle is off to the side! But, when manually leveling bed, it starts to come up, and it keeps going up and pushes really hard on the nozzle and i have to power it off. Should I change the Z_MAX_LENGTH to 189 or so and see if that helps with manual bed level or would that mess anything else up?

**Comment by moorer2k** [comment]
Yes I understand that part. I guess what I am asking is where would I need to look to check why the manual bed leveling is causing the bed to lift into the nozzle. After homing all, I disabled the steppers and moved the extruder over the bed and it has nice clearance so I’m not sure if it’s an offset I need to input into repetier or? Here’s some pics, just for fun :)
 
**new nozzle adapter**
![d27b709d-a58f-41d7-8651-d8d16f6f47f8](https://user-images.githubusercontent.com/2856413/51343797-0bd73280-1a4c-11e9-9883-e76eb665f36a.jpeg)

**z bracket for extended end stop triggering**
![ce83e21d-8c79-4c0f-9c22-0e9504c0d16e](https://user-images.githubusercontent.com/2856413/51343798-0bd73280-1a4c-11e9-8817-1c7581b15d94.jpeg)

**Comment by luc-github** [comment]
Then be sure in EEPROM Zmin is 0 
![image](https://user-images.githubusercontent.com/8822552/51345470-6186fb80-1a9b-11e9-9a54-c8b51c2e3934.png)

as well in your slicer if set

**Comment by moorer2k** [comment]
I also forgot to mention that I did not reinstall the z probe, is this pretty critical? It came with a new z probe to install, could this be the problem for the manual bed leveling? My z min is 0 yes.

**Comment by moorer2k** [comment]
![670d0d5f-a379-4b92-baa6-a1871e4d128e](https://user-images.githubusercontent.com/2856413/51345861-f87a9600-1a50-11e9-884a-ac7bededfd82.jpeg)
![c701182f-9339-441c-8c7f-07d3300f5e46](https://user-images.githubusercontent.com/2856413/51345862-f87a9600-1a50-11e9-9b23-7e9bf9b64b8b.jpeg)
![21eea564-7390-451c-bea1-5f5f7ed3024b](https://user-images.githubusercontent.com/2856413/51345865-f87a9600-1a50-11e9-8d62-587aeda72acb.jpeg)

**Comment by luc-github** [comment]
for manual bed levelling z probe is not used but yes do not use autobed leveling

**Comment by moorer2k** [comment]
Ok so I guess I was wrong... something must of reset a setting or something... it actually isn’t homing in the right position at all anymore. I was really tired {bare with me, I’m a narcoleptic, so much is like a dream to me}. When I home it’s now off even with the new bracket... I loaded the eeprom failsafe just to start fresh and make sure it’s stock. This what I’m dealing with distance wise now after homing.

![f1e54d2d-40d4-4c01-a4cd-72c3c6fc05e8](https://user-images.githubusercontent.com/2856413/51346324-362bee80-1a52-11e9-9e21-66739f0b801a.jpeg)

**Comment by moorer2k** [comment]
So if I set z min to 11, then home all, it the bed moves down to where I can clear it fine. But that won’t stay in effect when I do manual bed leveling. 
![image](https://user-images.githubusercontent.com/2856413/51346585-db46c700-1a52-11e9-8d39-324f3fb8508a.jpg)
![image](https://user-images.githubusercontent.com/2856413/51346606-e863b600-1a52-11e9-88b0-712e64de012c.jpg)

**Comment by moorer2k** [comment]
Ok I’ll give it a shot and let you know by the end of the day the outcome !

**Comment by moorer2k** [comment]
Ran into some more issues unfortunately... The PCB for the extruder seemed to have some bad pins for the thermistor, even the fans seems like they are both trying to break apart. One has severed completely off the board. I think i'll solder the fans directly to the the pins, and find a different way to connect the thermistors sensor back. Thanks again though for the information!
