### ISSUE TITLE
Can one re-flash without shorting jumper?

### ISSUE THREAD

**Issue by arpruss** [luc-github/Repetier-Firmware-4-Davinci#339]
I have a vague recollection that after flashing Repetier once, it was possible to re-flash a new version without shorting the jumper by using the MODE command in the Windows command-line and bossac. But I did this about a year ago and now I can't remember what the MODE parameters were for switching into upload and execute modes, and I can't find this information with Google anymore. Am I remembering wrong?

**Comment by luc-github** [comment]
You do not need to google it. Just read the readme. No need to use jumper for reflash
