### ISSUE TITLE
Unable to Flash Da Vinci 1.0A using repetier

### ISSUE THREAD

**Issue by CollinsCreations1** [luc-github/Repetier-Firmware-4-Davinci#341]
Sorry for the double post, I believe I commented on a closed section previously and this is my first time using GitHub. Hello I've been having ALOT of trouble bouncing between forums and videos figuring out the hard way as to which method is outdated. I am trying to flash my XYZ Da Vinvi 1.0A printer with repetier host software so that I may print with 3rd party filaments and use the Cura slicer. I've tried every Arduino version including 1.8.0 and have always added the correct Board through manager and selected the native USB option. I have selected COM 4 as this is the printer connection and have entered 1 for both of the configuration options. I started by flashing the printer by shorting the J37 pins and achieved the 2 black bars. I have transferred the correct hardware files from the repetier folder into the arduino folder. When I verify the arduino code it says successful however every time I upload to the printer even if it results in the code saying "upload complete/successful" the USB becomes unrecognized by my computer and the only way to re-establish the printer as "COM 4" again is by reflashing by shorting J37 again. It's been an endless loop of failure for me and I can't quite find the solution. As I've read from above there is a "Bossa Procedure" however I can't quite seem to find anything to walk me through it. If anyone has any recccomendations, I'd very much appreciate it!

**Comment by luc-github** [comment]
This is typical issue of variant.cpp no copied in proper location as described on FAQ
so original is still used.
What is the file location of the variant.cpp you updated ?
Give me full path pls

**Comment by CollinsCreations1** [comment]
I copied the file from the repetier folder found at

 C:\Users\colli\Desktop\Repetier-Firmware-4-Davinci-master\src\ArduinoDUE\AdditionalArduinoFiles\Arduino - 1.8.0 -Due 1.6.8\Arduino15\packages\arduino\hardware\sam\1.6.8\variants\arduino_due_x

to the arduino folder found at 

C:\Users\colli\Desktop\arduino-1.8.0\hardware\arduino

I noticed that the arduino file doesn't seem to contain the variant.cpp file orginally, so only the usbcore is replaced and the variant seem to be added rather than replaced. Sorry if i am wrong. Also I have posted 2 screen shots. The first shows where I copy the variant file from. the second displays that I do not have a file labeled "sam" to paste the variant into, therefore I can't get to the arduin due x file. 
Thank you so much for your feedback!
![original location of variant file](https://user-images.githubusercontent.com/47546688/52608472-bf5ef700-2e3f-11e9-8a6f-a71b89b60b6d.JPG)

![no sam folder under hardware](https://user-images.githubusercontent.com/47546688/52608481-c5ed6e80-2e3f-11e9-9a81-25dfb5aa2989.JPG)

**Comment by luc-github** [comment]
You need to download due module first like explained in readme step 3

**Comment by CollinsCreations1** [comment]
Is the step 3 pasted below you are referring to? If so, I posted a picture showing I have installed the due 1.6.8 from tools/board manager
3. Use an arduino IDE supporting arduino DUE, 1.8.0 with Due 1.6.8 module from board manager FAQ#166.
![board manager snip](https://user-images.githubusercontent.com/47546688/52609006-609a7d00-2e41-11e9-983f-55bf48015197.PNG)

**Comment by CollinsCreations1** [comment]
I have moved the variants file to this location, does this look correct? (Sorry I can't test it myself I am at the library but will test when I am home in 2 hours if it is the correct format?)
C:\Users\colli\Desktop\arduino-1.8.0\hardware\arduino\sam\1.6.8\variants\arduino_due_x
![new variant location](https://user-images.githubusercontent.com/47546688/52609311-70ff2780-2e42-11e9-85a7-d0f1eb0f9bf0.PNG)

**Comment by luc-github** [comment]
The target file is a replacement. So if no fale is not correct location. And Desktop is not arduino location. Did you follow step 4 Faq link ? It open right location

**Comment by luc-github** [comment]
FAQ#114

**Comment by CollinsCreations1** [comment]
Okay, I believe I transferred the files as they should be. I will update you when I am able to test this out on my printer in about an hour. Thank you so much for all the help so far!

**Comment by CollinsCreations1** [comment]
I cannot thank you enough, the printer booted into it's new firmware, thank you for helping me so patiently and sorry I was essentially reading over the obvious instructions and was caught in my habit for saving things to the desktop haha.
