### ISSUE TITLE
usb device not recognized

### ISSUE THREAD

**Issue by Handt21** [luc-github/Repetier-Firmware-4-Davinci#352]
I've followed every I could do and keeps saying usb device not recognized
![20191021_214337](https://user-images.githubusercontent.com/56856307/67256663-eb5e5d80-f44d-11e9-8679-4ed76e1e1236.jpg)

**Comment by luc-github** [comment]
printer is working ?

**Comment by Handt21** [comment]
No it's not working. I still have black bars on lcd

**Comment by luc-github** [comment]
so you followed FAQ about black bars ?

**Comment by Handt21** [comment]
Yes I've tried to fallow them but it's a little  confusing. Is anyone willing to help maybe teamviewer

**Comment by luc-github** [comment]
what is confusing ?
if you are not able to compile, why you do not flash the binary present in release ?
https://github.com/luc-github/Repetier-Firmware-4-Davinci/issues/109#issuecomment-373344462

**Comment by Handt21** [comment]
How do you do that.

**Comment by luc-github** [comment]
Did you click on link I gave you ?

**Comment by Handt21** [comment]
I will try it all over after work today

**Comment by Handt21** [comment]
So I believe I've done everything correctly but it stops at 79%

**Comment by luc-github** [comment]
https://github.com/luc-github/Repetier-Firmware-4-Davinci/issues/185

**Comment by Handt21** [comment]
I got it. Sorry I didnt message back right away. Thank you for the help.

**Comment by luc-github** [comment]
good
