### ISSUE TITLE
Printer non responsive after print

### ISSUE THREAD

**Issue by tomnmisty** [luc-github/Repetier-Firmware-4-Davinci#362]
First off I love the firmware for the xyz. Thank you for the hard work. I have owned this printer for 3 years and can’t believe I wasted all that time without doing this upgrade. Anyway, I am using Mac OS with repetier host to send gcode to the printer. Everything works perfectly except when a print is done I can’t communicate with the printer any longer. I have to manually power cycle the printer and reconnect to it after each print. I can’t manually send gcode after a print like I can after the power cycle.  It will just say 1 command waiting on the Mac repetier screen and count up with each button push. Not a big deal just kind of irritating.

**Comment by luc-github** [comment]
hmm looks like repetier host issue not FW issue
