### ISSUE TITLE
Firmware Installed Constant Restart

### ISSUE THREAD

**Issue by TheOfficialCzex** [luc-github/Repetier-Firmware-4-Davinci#363]
The firmware seems to be installed (the LCD UI is functioning, the EEPROM was loaded...), but the printer keeps restarting every 30 seconds or so.

**Comment by TheOfficialCzex** [comment]
My guess is that it's watchdog-based.

**Comment by luc-github** [comment]
yes look like

**Comment by TheOfficialCzex** [comment]
This is my first time dealing with anything Arduino-based, so I have no idea what I'm doing. How would I go about disabling watchdog or setting a loop trigger for it?

**Comment by luc-github** [comment]
how did you opened issue ? there is a template for support

**Comment by TheOfficialCzex** [comment]
Template?

**Comment by luc-github** [comment]
yes when you open issue in github there is a template of questions to help for support.
I do not see them, so I am wondering how do you submit issue, you are not using github interface?

**Comment by TheOfficialCzex** [comment]
I just created a new issue. Maybe you can't create an issue for your own release?

**Comment by luc-github** [comment]
So when you create issue you do not see these ?

![image](https://user-images.githubusercontent.com/8822552/79302580-16050c80-7eed-11ea-81cb-dff06061cba8.png)


![image](https://user-images.githubusercontent.com/8822552/79302491-d3dbcb00-7eec-11ea-9364-c68960352fcd.png)

![image](https://user-images.githubusercontent.com/8822552/79302521-e8b85e80-7eec-11ea-940c-29868a7a5b9b.png)

or do you open differently ?

**Comment by TheOfficialCzex** [comment]
I think what happened was I started an issue without logging in, and, somehow, logging in between starting an issue and actually submitting it prevented me from seeing that page.

**Comment by luc-github** [comment]
indeed - looks a bug in github
about issue now
 I need some info as you were not able to see the template:

**PC (please complete the following information):**
 - OS: [e.g. iOS]
 - Arduino Version [e.g.1.8.0]
 - Due Module Version [e.g. 1.6.8]

**Printer
- Type: [e.g. Duo 2.0, 1.0A, 1.0, AiO, Duo 2.0A]

**Firmware (please complete the following information):**
- Branch used [e.g. master branch]
- Version displayed in printer menu Settings/Sytem Version
- Configuration used in configuration.h
- Did you modified the code ?

**Comment by TheOfficialCzex** [comment]
Windows 7
1.8.12
1.6.8
Master
0.92.10
0 (1.0A), 1 (J37), 0 (no added fan control)
Beyond the config, no.

**Comment by luc-github** [comment]
Ok there is one possibility is that the 1.8.12 has some incompatibility - I used 1.8.0 and some more recent  and I had no issue, but I never used 1.8.12 for Davinci 

another solution is to disable the watchdog here : https://github.com/luc-github/Repetier-Firmware-4-Davinci/blob/master/src/ArduinoDUE/Repetier/Configuration.h#L1580

`#define FEATURE_WATCHDOG 0`

and see if there is another problem with hardware

**Comment by TheOfficialCzex** [comment]
Setting line 1580 to 0 completely fixed it. The printer runs without a hitch.
