### ISSUE TITLE
Total Noob with a DaVinci 2.0 (I think) printer - what are my firmware options?

### ISSUE THREAD

**Issue by jorythompson** [luc-github/Repetier-Firmware-4-Davinci#367]
Hi all,
I have a hand-me-down DaVinci printer.
The first screen says DA VINCI 1.0
INFO says SYSTEM VERSION 2.1.2
There is a J37 jumper on the back motherboard

What can I do with this version of printer?

thanks in advance,
Jordan

**Comment by luc-github** [comment]
Solved per gitter discussion
