### ISSUE TITLE
Duo 2.0 X/Y location of print heads (both left and right) is over scraper while loading filament

### ISSUE THREAD

**Issue by JacobChrist** [luc-github/Repetier-Firmware-4-Davinci#371]
**Describe the bug**
X/Y location of print heads (both left and right) is over scraper while loading filament.  This causes the newly loaded filament to extrude into the scraper gunking it up.

**To Reproduce**
1. From home screen press right arrow button.
2. Select Maintenance
3. Select Load/Unload
4. Select Load Left (or Right)

**Expected behavior**
Hot ends should be a bit further forward so as to clear the scrapers.

**PC (please complete the following information):**
Win 10
Arduino Version: 1.8.13
Due Module Version 1.6.8

**Printer
Duo 2.0 (no sure if its an 2.0A or not) w/J77
Main PCB Marking: 
F1.x F2.x Engine board F2
3DPO3-ES008
2014/08/01
Marked ICT, FCT1, VI

**Firmware (please complete the following information):**
Branch used [master] 445fa50
Version displayed in printer menu Settings/Sytem Version
Configuration used in configuration.h:
```
#define DAVINCI 3// "0" if not DAVINCI, "1" For DAVINCI 1.0, "2" For DAVINCI 2.0 with 1 FAN, "3" For DAVINCI 2.0 with 2 FAN, 4 for AiO (WITH NO SCANNER SUPPORT)
#define MODEL  1//"0" for first generation (jumper JP1 to reset ) , "1" for new generation   (jumper J37 to reset)
#define REPURPOSE_FAN_TO_COOL_EXTRUSIONS 0 //Setting this to 1 will repurpose the main Extruder cooling fan to be controlled VIA M106/M107
                                           //Warning: for DaVinci 1.0 need to add a permanent fan with power supply to cool extruder
```

Did you modified the code: No

**Comment by luc-github** [comment]
I do not have Duo2A and position is based on homing position of my Duo2.0 but I know the scraper position changed with new generation 
Can you share a picture of the position of each extruders when home position - and when load/unload ?
also use the menu to move the extruder to put it in right position and give me the both positions ? So I can adjust the positions

**Comment by JacobChrist** [comment]
The right extruder (labeled 1 on the printer) wants to be at X=0mm Y=30mm
The left extruder (labeled 2 on the printer) wants to be at X=195mm Y=30mm


Head over left extruder.
![20210111_100040](https://user-images.githubusercontent.com/198251/104227375-21df1a00-53fe-11eb-8d7b-7276e87ed853.jpg)
Close up with head over left extruder.
![20210111_100018](https://user-images.githubusercontent.com/198251/104227327-0bd15980-53fe-11eb-9e8d-c86353350e8f.jpg)
Head away from extruder after loading (black glob in scraper is PLA).
![20210111_100140](https://user-images.githubusercontent.com/198251/104227434-3f13e880-53fe-11eb-8426-f15e757a7d4b.jpg)
Main board picture:
![20210110_113854](https://user-images.githubusercontent.com/198251/104227489-5357e580-53fe-11eb-829c-4c0ae8939f27.jpg)


P.S. Loving the firmware sidegrade!  The motion is so much smoother over stock firmware and it detects broken filament!

**Comment by luc-github** [comment]
Ok Thank you - so I will add a define for the load / unload unload position in configuration.h according config
it should allow to correct position in case of problem - I will do this tomorrow

**Comment by luc-github** [comment]
please give try to latest git - https://github.com/luc-github/Repetier-Firmware-4-Davinci/commit/1fcc1d041231c231bee23747710665f446f3ed55

**Comment by JacobChrist** [comment]
Seems to work pretty good.  I may have been off, when the goop coming out of the hot end it looks like a y=25mm might be better.

**Comment by luc-github** [comment]
you can adjust the values here https://github.com/luc-github/Repetier-Firmware-4-Davinci/blob/master/src/ArduinoDUE/Repetier/Configuration.h#L1152-L1154 
SVP try and report me the best one

**Comment by luc-github** [comment]
@JacobChrist did you finalized the proper x and y  ?

**Comment by JacobChrist** [comment]
I will try to get some numbers over the weekend.

Jacob

**Comment by JacobChrist** [comment]
Luc,

27 mm is the number I would go with.  25 mm is cutting is a bit close to
the scraper and 30 mm is close to the edge and when loading the printer the
extruded filament spills over the catch.

Jacob

**Comment by luc-github** [comment]
done https://github.com/luc-github/Repetier-Firmware-4-Davinci/commit/84c107b10f49eb3ee85d6b531e7a6ad8c77850a3 thank you  ^_^
