### ISSUE TITLE
[Question] Verification fails at 69%

### ISSUE THREAD

**Issue by feoranis26** [luc-github/Repetier-Firmware-4-Davinci#375]
I uploaded this firmware properly to my printer a few times before but when I tried to update it now it just gets stuck at verification at 69%

**Comment by luc-github** [comment]
https://github.com/luc-github/Repetier-Firmware-4-Davinci/discussions/185

**Comment by feoranis26** [comment]
I uploaded successfully a few times previously today, I didn't change anything with my setup between flashes. USB communication is good.

**Comment by luc-github** [comment]
cable close to light / or any power supply may disturb, also be sure upload speed is not too fast etc.. 
This part is definitly hardware / arduino related
