### ISSUE TITLE
[Question] Why does the bed and nozzle heat up when leveling the bed?

### ISSUE THREAD

**Issue by cirvladimir** [luc-github/Repetier-Firmware-4-Davinci#384]
Why does the bed and nozzle heat up when manually leveling the bed? It seems unnecessary and inconvenient.

**Comment by luc-github** [comment]
because to do proper leveling should be in same situation as printing when leveling the dilatation must be take in axxount

**Comment by cirvladimir** [comment]
That makes sense, thanks.
